
name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - name: deploy the website to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: meal-database-app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels